[package]
name = "simple_mod_int"
version = "0.1.0"
edition = "2021"
keywords = ["mod", "int", "math", "integer"]
description = "A simple modint library"
license = "MIT"

[dependencies]
num-traits = "0.2"